### ISSUE TITLE
problem with expert induction

### ISSUE THREAD

**Issue by szumx123** [adaa-polsl/RuleKit-python#21] opened 2024-02-15 10:39 UTC
During expert induction using expert knowledge, a `java.lang.NullPointerException` error appears (I used examples from the documentation). The error occurs only for classification and regression. I am attaching a notebook and data for simpler reproduction of the error.
[expert_induction.zip](https://github.com/adaa-polsl/RuleKit-python/files/14295588/expert_induction.zip)

**Comment by cezary986** [comment] 2024-02-20 09:13
Thank you for reporting this issue. It seems to be a duplicate of Issue #14.  Expert induction at the moment lack any kind of validation of the rules and conditions you pass into ExpertRuleClassifier.fit method. In this specific case it was the fault of the rules and conditions containing `gimpuls` attribute. There is not such attribute in the dataset you've provided. Currently the package will fail badly in such case.

**Closed** 2024-02-20 09:13 UTC
Labels: duplicate
